### ISSUE TITLE
Re-open issues and PRs that are closed wrongly

### ISSUE THREAD

**Issue by brianamarie** [teacher-bot/teacherbot#13]
_Originally posted in github/teacher-bot_

For those lovely instances when someone may close issues and pull requests for other people, we could have a bot open those back on up. 

I don't know how this could function for pull requests that are _merged_.

We could also create a behavior where at first the bot re-opens and warns the user who closed them, but if it continues, they are blocked and the training team is notified. 

_Originally commented by @JasonEtco_ 

Also add whitelist to ensure that maintainers/owners/admins can override this functionality.

**Comment by hectorsector** [comment]
Development for this has been attempted, but we hit a snag when trying to reopen an issue via the API, and opened [an bug report for `node-github`](https://github.com/mikedeboer/node-github/issues/552#issue-239318576) about it.

**Comment by crichID** [comment]
> opened an bug report for node-github about it.

@hectorsector do you know if the newest version [fixed it](https://github.com/mikedeboer/node-github/issues/552#issuecomment-326420306)? I believe we said we would test but I'm not sure if it happened yet. Also, I wonder if this could somehow be related to the problems we are having with how bot users are treated?

**Comment by hectorsector** [comment]
> do you know if the newest version fixed it?

I did some testing myself and it did not. 

> Also, I wonder if this could somehow be related to the problems we are having with how bot users are treated?

I wonder the same!

**Comment by brianamarie** [comment]
@hectorsector @crichID I closed the bug report issue in `node-github` since he provided an example and says it works  - and I never tested like I said I would. 😬 

I said we would re-open if we had more questions. @hectorsector I'm would love to help re-test this but I don't know when I will have the bandwidth for a while. Maybe we could put some time aside to pair around Universe time?

**Comment by hectorsector** [comment]
Good news! The node wrapper checks out. I've [started to develop](https://github.com/teacher-bot/reopen-closed-issues) this plugin. However, it isn't neat and still requires the ability to look for PRs (in addition to issues).

Any help is appreciated, @teacher-bot/training-team @JasonEtco ❤️

**Comment by brianamarie** [comment]
I'm going to close as this is stale, but please feel free to reopen. 💖
