### ISSUE TITLE
If Travis build fails, post different response

### ISSUE THREAD

**Issue by brianamarie** [teacher-bot/teacherbot#19]
Recently, we've had [a complaint](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/13022) about not having enough documentation for solving broken Travis builds in on demand. 

Maybe Teacherbot, the app that already helps for a few tests, would watch for a failing build. If the status is failing, then Teacherbot could post a comment with some basic instructions for how to see and interpret the test results. What do you think @hectorsector @teacher-bot/training-team?

**Comment by crichID** [comment]
> If the status is failing, then Teacherbot could post a comment with some basic instructions for how to see and interpret the test results.

@brianamarie I :heart: this! I wonder if we could re-use the video to show how to fix common problems as a short term fix: https://vimeo.com/201011288

**Comment by brianamarie** [comment]
@crichID That sounds like a good idea to me. We try to post that when we come around on comms duty, but if Teacherbot could comment it automatically when a status fails, it would probably be much more useful to the learner. 

@crichID @hectorsector @JasonEtco Is my understanding correct that we would need to create an entire new repository under the `teacher-bot` organization and then include that code as a dependency in this repository? Do any of you have an idea for how long it would take to code this feature?

**Comment by hectorsector** [comment]
I'm more inclined to do away with Travis tests altogether in favor of more Teacherbot statuses. What do you think, @brianamarie? That is, unless we were to launch a course specifically on CI.

**Comment by JasonEtco** [comment]
Related, I've been working on a `CI-Reporter` Probot app that copy-pastas error logs into the failed pull request. Its still very much a WIP: https://github.com/jasonetco/ci-reporter

**Comment by brianamarie** [comment]
> I'm more inclined to do away with Travis tests altogether in favor of more Teacherbot statuses.

❤️ 😍 LOVE this. 



> Related, I've been working on a CI-Reporter Probot app that copy-pastas error logs into the failed pull request.

I love this too!!!

**Comment by brianamarie** [comment]
I'm going to close as this is stale, but please feel free to reopen. 💖
